### PR TITLE
added PNG version of SocketCAN-logo

### PR DESCRIPTION
**Pull request by alan707**
The purpose of this addition is to link the PNG version of the logo to the can-utils README.md

### CODE REVIEW

**Comment by hartkopp** [comment]
There's now a new directory 'png' that contains different resolutions of all logos.
Thanks Alan!

**Comment by alan707** [comment]
Cool! what was your thought process for not merging in the pull request this time?  Anything wrong with the PNG file?

**Comment by alan707** [comment]
the cost between merging and closing valid PRs is equal, but one makes contributors happy and the other drives them away from your projects

**Comment by hartkopp** [comment]
1. 1 PNG vs 15 PNGs in three different resolutions each
2. re-order and creation of two directories
3. README with PNG overview

What should the merge a single PNG with an unknown DPI value help there?

**Comment by alan707** [comment]
There are two ways to accept the pull request for this particular case:
1) You merge the single PNG pull request in and then add the other 14 PNGs, re-order creation of directories and improve README on your own
or
2) You request that I change the pull request and re-submit 15 PNGs with different resolutions before you merge it.  Once the changes are to your satisfaction, you merge that pull request in.  You can still commit your changes after (like adding directories, improving README).  There is no penalty that I am seeing in doing it this way, but perhaps I might be missing something?

What I like about this Github way of open source is that you involve the contributor to continue improving and also help reduce the workload on your side of maintaining the repo (less work for you).  Just a thought, you can continue doing it the same way you are doing it now, but maybe worth giving it some pondering for future pull requests.

**Comment by hartkopp** [comment]
I did some experiments on my own to check which different picture sizes would make sense to me. I would have had more effort to tell you about my detailed intention than to do it on my own.
And in fact I am happy still to be able to do things on my own. Telling people how things should have to be done and do thousands of boring cycles about it is my daily work and creates more mental effort for me than relaxing while watching TV and using Inkscape to export 15 PNGs.

**Comment by alan707** [comment]
Ok, that is a very good point!  Also, the fact that you use Inkscape is a a big plus 👍  Thanks for the explanation.  Are there any other things on the can-utils repo that you would like to improve or things that you'd like someone to help with?

**Pull request closed without merging**
